title: MadH4ckr
author: Chuck J.
email: h4ck.701@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  I am Writing this as my message.

# social links
twitter_username: tweet # DO NOT include the @ character, or else the build will fail!
github_username:  h4ck701 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
